packages:
  - 'backend'
  - 'frontend'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': false
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '@swc/core': false
  prisma: false
  sharp: false
  unrs-resolver: false
